version: "3.0"
   
services:
  web_service:
    build: 
      context: ./
    env_file:
      - .env.dev
    container_name: Gmail_app
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/backend
    ports:
      - "8011:8000"
    restart: always
    networks:
      backend_net:

networks: 
  backend_net:
    driver: bridge